region          = "us-east-1"
aws_profile     = "arn:aws:iam::930837413038:user/exec-local"
environment     = "sandbox"
initial_db_name = "ObsidianDatabase"
master_password = "daferw4356u7ikumghnfrge5y46ui7yukgyh"
master_username = "rordakadmin"
