region          = "us-east-1"
aws_profile     = "arn:aws:iam::975050069061:user/blackstone-tf-local-exec"
environment     = "sandbox"
initial_db_name = "BlackstoneDatabase"
master_password = "daferw4356u7ikumghnfrge5y46ui7yukgyh"
master_username = "rordakadmin"
